- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "22"
- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"
- name: pause
  pause:
    seconds: 15
- name: Update ansible + install sshpass for ansible asking password + keychain
  apt:
    pkg:
      - ansible
      - sshpass
      - keychain
      - openssh-client
    state: latest
    update_cache: true

- name: fix iptables to use services on WSL
  shell:
    cmd: |
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24"
