- name: operations as user
  become: true
  become_user: "{{myuser}}"
  block:
  - name: check if dest ssh dir exist "{{item.dest|dirname}}"
    stat: 
      path: "{{item.dest|dirname}}"
    register: ssh_dir
  - debug: var="item.dest|dirname"
  - debug: var=item.src_priv
  - name: create ssh dir if not present
    file:
      path: "{{item.dest|dirname}}"
      state: directory
      mode: '0700'
    when: not ssh_dir.stat.exists
  - name: copy windows ssh private key
    copy:
      remote_src: true
      src: "{{item.src_priv}}"
      dest: "{{item.dest}}"
      mode: '0600'
  - name: check if windows ssh public key present
    stat: 
      path: "{{item.src_pub}}"
    register: id_rsa_pub_windows_present
  - name: copy windows ssh public key
    copy:
      remote_src: true
      src: "{{item.src_pub}}"
      dest: "{{item.dest}}.pub"
      mode: '0600'